sentence_counter:
  spacy_model_name: "en_core_web_sm"
credentials:
  type: gcp
  credentials-list:
    - env_var: OPENAI_API_KEY
      secret_name: projects/news-cummings/secrets/OPENAI_API_KEY/versions/latest